version: '3.9'
services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - api-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Weather_App_Calendar_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      # POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:setup && bundle exec rails s -p 3001 -b '0.0.0.0'"
    restart: always
    environment:
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=secret
            - RAILS_ENV=production
            - DATABASE_HOSTNAME=postgres
            # - DATABASE_URL=postgres://postgres:secret@postgres:5432/Weather_App_Calendar_api_production?pool=5
            - SECRET_KEY_BASE=d4df6d90bb36b2b3c1f0e19592fa183c22846512b87cdb148f41fe67eb6901c48e467dde1038da7820bed13f45a3030feef92df121a772954de2bd36596b34bf
            - RAILS_MASTER_KEY=d20ad351b961025e89204f525ae5adb9
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    name: my-pre-exiting-network
    external: true
volumes:
  api-psql-data:
