services:
  db:
    image: postgres:14
    hostname: db
    restart: always
    ports:
      - 5432:5432
    volumes:
      - api-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Weather_App_Calendar_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rake db:setup && bundle exec rails s -p 3001 -b '0.0.0.0'"
    restart: always
    environment:
            - DATABASE_HOSTNAME=postgres
            - DATABASE_USER=postgres
            - DATABASE_PASSWORD=secret
            - RAILS_ENV=production
            - DATABASE_URL=postgres://postgres:secret@db:5432/Weather_App_Calendar_api?pool=5
            - SECRET_KEY_BASE=d20ad351b961025e89204f525ae5adb9
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  api-psql-data:
