services:
  db:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    volumes:
      - api-psql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: Weather_App_Calendar_api

  app:
    build: .
    command: bash -c "bundle exec rake db:setup && bundle exec rails s -p 3001 -b '0.0.0.0'"
    ports:
      - 3001:3001
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  api-psql-data:
